{%set name = "pydruid" %}
{%set version = "0.3.1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "a9016cee3dcfe98d7d6d98be1d710c6b055259a921ce2a9e896c73524cc5a30f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - six >=1.9.0

  run:
    - python
    - six >=1.9.0

test:
  imports:
    - pydruid
    - pydruid.utils

about:
  home: http://pypi.python.org/pypi/pydruid/
  license: Apache 2.0
  summary: 'A Python connector for Druid.'

extra:
  recipe-maintainers:
    - pmlandwehr
