{% set name = "pydruid" %}
{% set version = "0.4.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "427330cb1deb921398fe4cc929d002edb6cf271b9d50914b6edc49708bdfe1ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pydruid = pydruid.console:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest-runner

  run:
    - python
    - six >=1.9.0
    - requests
    - pandas
    - tornado
    - sqlalchemy
    - pygments
    - prompt_toolkit
    - tabulate

test:
  imports:
    - pydruid
    - pydruid.utils

about:
  home: https://github.com/druid-io/pydruid
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'A Python connector for Druid.'
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid/

extra:
  recipe-maintainers:
    - pmlandwehr
