{% set name = "pydruid" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30b6efa722234183239296bf8e6d41aba7eea0eec3d68233ce6c413986864fea

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pydruid = pydruid.console:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # Keep optional dependencies as we already provided them in the run section
    - pandas
    - prompt_toolkit >=2.0.0
    - pygments
    - requests
    - sqlalchemy <2
    - tabulate
    - tornado

test:
  imports:
    - pydruid
    - pydruid.utils
  requires: 
    - pip
  commands: 
    - pip check

about:
  home: https://github.com/druid-io/pydruid
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: A Python connector for Druid
  description: |
    pydruid exposes a simple API to create, execute, and analyze Druid queries. pydruid can parse query results into Pandas DataFrame objects for subsequent data analysis -- this offers a tight integration between Druid, the SciPy stack (for scientific computing) and scikit-learn (for machine learning). pydruid can export query results into TSV or JSON for further processing with your favorite tool, e.g., R, Julia, Matlab, Excel. It provides both synchronous and asynchronous clients.
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid/

extra:
  recipe-maintainers:
    - pmlandwehr
