{%set name = "pydruid" %}
{%set version = "0.4.2" %}
{%set hash_type = "sha256" %}
{%set hash_val = "07ef6034a5066b2fa6aa745bb2beb00fdbfb59ece5b50b1dcc8124ca972d7ad8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner

  run:
    - python
    - six >=1.9.0
    - pandas
    - tornado

test:
  imports:
    - pydruid
    - pydruid.utils

about:
  home: https://github.com/druid-io/pydruid
  # license_file: Not in MANIFEST - see https://github.com/druid-io/pydruid/pull/77
  license: Apache 2.0
  license_family: Apache
  summary: 'A Python connector for Druid.'
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid/

extra:
  recipe-maintainers:
    - pmlandwehr
