{% set name = "pydruid" %}
{% set version = "0.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydruid-{{ version }}.tar.gz
  sha256: 63c41b33ab47fbb71cc25d3f3316cad78f18bfe947fa108862dd841d1f44fe49

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - pydruid = pydruid.console:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    # Keep optional dependencies as we already provided them in the run section
    - pandas
    - prompt_toolkit >=2.0.0
    - pygments
    - requests
    - sqlalchemy <2
    - tabulate
    - tornado

{% set deselected_tests = [
  "--deselect=tests/db/test_cursor.py::CursorTestSuite::test_ssl_client_cert_authentication_with_patch_imported"
]%}

test:
  imports:
    - pydruid
    - pydruid.utils
  source_files:
    - tests/
  requires: 
    - pip
    - pytest
    - pycurl
  commands: 
    - pip check
    - pytest -vv {{ deselected_tests | join(" ")}} # [not win]
    # AssertionError on win for test_export_tsv, test_writerow, test_writerows
    - pytest -vv {{ deselected_tests | join(" ")}} -k "not (test_export_tsv or test_writerow or test_writerows)"  # [win]

about:
  home: https://github.com/druid-io/pydruid
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: A Python connector for Druid
  description: |
    pydruid exposes a simple API to create, execute, and analyze Druid queries. pydruid can parse query results into Pandas DataFrame objects for subsequent data analysis -- this offers a tight integration between Druid, the SciPy stack (for scientific computing) and scikit-learn (for machine learning). pydruid can export query results into TSV or JSON for further processing with your favorite tool, e.g., R, Julia, Matlab, Excel. It provides both synchronous and asynchronous clients.
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid

extra:
  recipe-maintainers:
    - pmlandwehr
