{% set name = "pydruid" %}
{% set version = "0.5.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "ea4556c3991844dd9ba2db0da2089020682d9266aac81804879ad8cbaa46dd3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pydruid = pydruid.console:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest-runner

  run:
    - python
    - six >=1.9.0
    - requests
    - pandas
    - tornado
    - sqlalchemy
    - pygments
    - prompt_toolkit
    - tabulate

test:
  imports:
    - pydruid
    - pydruid.utils

about:
  home: https://github.com/druid-io/pydruid
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'A Python connector for Druid.'
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid/

extra:
  recipe-maintainers:
    - pmlandwehr
