{%set name = "pydruid" %}
{%set version = "0.3.1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "a9016cee3dcfe98d7d6d98be1d710c6b055259a921ce2a9e896c73524cc5a30f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.9.0
    - pandas
    - tornado

test:
  imports:
    - pydruid
    - pydruid.utils

about:
  home: https://github.com/druid-io/pydruid
  # license_file: Not in MANIFEST - see https://github.com/druid-io/pydruid/pull/77
  license: Apache 2.0
  license_family: Apache
  summary: 'A Python connector for Druid.'
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid/

extra:
  recipe-maintainers:
    - pmlandwehr
