travis:
  secure:
    BINSTAR_TOKEN: bDmcGCHvQUmMby27Pca+OfvBUWzUwoAe6dEEYXFMKiMvBipwroMSFGD8XPeMHJd20rDUsEyDM9F7vCF0O38/mezJj+wdkUIwPBWUklYOD3y7x3tMbRlUHLwBZbPtAD9JbwDaGoJqR2jHyM8Kbs+rDh4Syg6Wl1PfBO6NnpCk75cAPUAoyI/JY3ntY+CmMFUh7unEqdrPN+4EneZxHcou19jxxqwg9GrtPL4zPXCBcGop+qLdEZG2nUixnH1krMpted3ir7OLHE0NvBBBLgl03qnd5VeoIIDp+039A7c2I5X2P9/Diw7s0VbNkG01zvOPIAvawo1I08BANI8HGUDdaEHxE6WenDQ8S0emm91bs1aqO8sib+uekKia9PHs9GHvvAx+16BAuIjgfPTVaxYUeTJ8BtF4C+fZy1IScRMvn1aWltjdktbsYvL3w4NEbgKRIGxRcfSpkuLi/cEG5wVqQUrczyg5oCdFppYVH6BUcXCN7ppt1hZE7gLAjVkATCCvngBGzKZMmE/BiE62McsoxF5/qjcNHzt++cvDdJqVOLg0wvXy+3ixGfHwN/Jt0ZCWl+suPpXDUpd/ewDq2YXjWHKGG5Z8hKZ7fs86aNHAJ3Kzlqgm66c/5IbBjyg902+E9HNsn4CM8n6yp2WCzOuZTwnXdTOoalqzoH2wvRzWTqs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
