travis:
  secure:
    BINSTAR_TOKEN: file5io+N/oqGLhQtXPNB/5BvCYCYKKNPOEJZrYaP4ygxV4t7DLkorgiYYjJJTSerxSJg57ykmWTb26Kg+TozwzJo6ZUn0pDga09B+YTmWfoWSke3QnqQ8lOnHYmBYjOVGRnTqzNYansx0ZgNdicxK8HyfUTMg6Proc7+kXtOH6Rb0oBffOQzw5ZjqXofOw9nnWD2jk3gEDQdb5Z//F1fLkkj3Lv6a5RaAmJR07vz2u2glQj5QIryHQHBZkDSjFSZh6CtXplfeP3zGgS/JIScdqkUCOE6212gqvkke4E9sdmP8t3qtEz6yCQkKHvz2o06GOD6plcedFjqGxk7vQwj23KaA7Ve94FqbLwoBV+JAd2VAw8dlYEAMGX9ebbAi/EgKwKMN27TV9e7RXBGgd/jr6R7gbk+QRzVHB+1gFJOcS7wyRVKPi7Q6e3Xci2Z64V6xqqhjAHHNM9LrLmqG/qxeaa9x7K7/siO2L+r7ZT3/cRQK7c4f8u7sE6MRJ4x0IF1Hci2uwSWj7Z1GKe99fZsr3PCSdWZR5Sc2LM7VmsyABXbnPyQ5NbQRRCXbRPdXtnCnwEqrr1zF68IDVk87xu1Z/vruzi0124jKRbkkAeDxNU3YhurKUlr8DfCragr9GsLXUro7KOv919Xx1DjRKzMr52TZHJvC864FkEWA0FERQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
