travis:
  secure:
    BINSTAR_TOKEN: P69WuxUIXmCV1IFMNHtKnkXeyJjLDk9Ydb/GpQReYttJRy5g+Vaq31x/FajCLl1UDfIe5ue7hclLvCLaGkzXLRiNvgcqbBU8fnkj4pkOdkekmq4KE8PT5zGmHul0akmM4tfcfVWL89LvvKTWyn5ztYzEYcMcOplJB0faOPfYG8h//tIk2t7p3WcCbtC+Rze6g/wPPVlHVxxSeXeh4uAsFTChFmdCqyJmTbZiSnQccmmJyvcR4PtnfKnXKYZvvFtzIAzDlMMg7P4eiJOuR9FH3/mv3O/HtrzFk9JVN+QTsuLksI6XnTSUiiYB4A6Yf87YMVdTXHp45iBwQ/vJ5ifnLK8CRvjbdn6qJlj1pynuEnRBUxCq66ikfVsfQ0pdqPI6J2Gk3BifU8XaWvpBHOadYuljEgsraXS8yhzE3sOicZwnBNe4RQDFmOrfqlE70S0qSoJBdJ27Os8egkeGaMwS2hac1E7p+Imu5j+YCI1QfO9c8W3vlry2fMe2Y1Vfh3In3Sg/qyo31S/PtvEzF+S5JFwVGFrGD1/41MMsrFfMDu65Gxiwgh9PO0Sd8IASNnICqT5xoD4eJUoXhuwQMkPYaInBvFaiY9be4Bir5/LMOynXPjiJCET5AwPoeyBMvjqTwvri/2mRjBrex78EKxxbJKTU858UxbW3KjqroHuC7KU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
